### ISSUE TITLE
no such file or directory realconfigs/shared.yaml

### ISSUE THREAD

**Issue by okok1234** [Kr4ken-9/DAB#42]

**Comment by Kr4ken-9** [comment]
This is an error on my part. It happens because when I am developing or using this project I use config files that aren't pushed to the github (due to having discord tokens in them) located in the realconfigs directory, I would fix it but there are uncommitted changes right now and I don't want to merge them, and as of right now I don't know if I want to continue this project. However, for future reference and for others experiencing this issue (since anyone using this project will encounter it) I will describe how to fix it.

The issue stems from Line 41 of main.py: https://github.com/Kr4ken-9/DAB/blob/master/main.py#L41
Simply remove "Real" from "RealConfigs/Shared.yaml" and this will be fixed.
