### ISSUE TITLE
Support for user tokens that have extra characters in them

### ISSUE THREAD

**Issue by 0xf0ld** [Kr4ken-9/DAB#51]
So my token seems to have extra characters in them that aren't normally found in traditional user tokens. Mine has the prefix `mfa`, then a period, then far head is a hyphen, and then finally an underscore. Example:
`mfa.975MW9QWMQQWJW8jfw38f23j89f-A9vj3FNAOFEJGHHN_sjc209fj`
Since tokens are authentication-related (hence changing password resets it), I presume the mfa is multi-factor authentication as I use 2FA.

How would I go on about using my token as putting it in the Shared.yaml hangs the script?

**Comment by Kr4ken-9** [comment]
My main account also has 2FA so I did some testing with it. After debugging, it looks like you will actually receive messages when using the mfa token, so it works to some extent. However, I also encountered the hang and I don't think DAB did anything else besides receive the messages.

I did some googling, and 4 years ago you were supposed to be able to login with mfa tokens. However, there are not much more recent resources on that. There are some people who had similar questions as us and asked them on official communities, and they are basically told they're going to be banned lol.

So, I am assuming this functionality has either been broken in those 4 years and they intentionally didn't fix it, or they even intentionally removed the ability to login with mfa tokens.

Either way, unless someone smarter than me can fix this, I don't think it will be possible to use DAB with mfa tokens.

**Comment by Kr4ken-9** [comment]
I did some more testing and I think, in my case, the hang is actually related to my discord account rather than the mfa. I disabled 2FA from my account and used the new, non-mfa token, and DAB still hangs. I still receive messages and whatnot though.

I don't know if it is the same in your case, but I think I'll have to investigate further.

**Comment by Kr4ken-9** [comment]
This has been fixed in this commit: https://github.com/Kr4ken-9/DAB/commit/ebafa4158bbc5075f06435abd610a1afab5f0d9f

The issue turned out to not be related to mfa tokens, and was actually related to fetching offline members. I believe the issue lies with when discord hides the offline members for large discord servers. So, both of our accounts were probably in large discord servers where the offline members were hidden.

Looks like previously users could get the offline list regardless using the bot library, and discord fixed that. So then DAB was running into some trouble still trying to retrieve the offline members.

Turned out to be easily fixed with a parameter inspired by this issue: https://github.com/Rapptz/discord.py/issues/2567 where the people were generally unhelpful except for one person who suggested it had something to do with guild chunking.

So based on what he said I started looking through the discord.py library to see how it handles "guild chunking" and to be honest I don't know why they call it that, because it seems to have more to do with "chunking" the huge list of offline members, rather than the guild itself.

Either way, as you can tell it took me some time to wrap my head around it, because I am new to interacting with APIs. I played around with it and found that skipping fetching the offline member list actually fixes this problem as far as I can tell.

I think the author of that issue had the right idea except he opted to use the AutoShardedClient for whatever reason, and I think that caused him to run into another issue. But his parameter solved our problem, and now we're using it.

I can't think of any functionality that will break due to not having the offline member list, so hopefully we won't run into any problems. And anyway, I don't think users are supposed to have access to the offline member list anyway, so this will hopefully make DAB appear more human.

Hopefully you can confirm this fix works for you, and if it does you can close this issue.

**Comment by Kr4ken-9** [comment]
I am going to close this because it's been a week and I have been using the bot on and off with this fix with no problems. I am going to assume it's been fixed.
