### ISSUE TITLE
need help with hashes.

### ISSUE THREAD

**Issue by PHEXO** [Kr4ken-9/DAB#57]
is there a way i can contact you though and can you please provide 32 character hashes of pokemon. i really need them. thanking you in advance. please attach your discord account username if you can.

**Comment by Kr4ken-9** [comment]
I do not publicly provide contact information outside of GitHub.

I also do not have a way to provide you with 32 character hashes of pokemon. Can I ask you what you need them for? If you want, you can generate hashes of configurable size with some files included in the repo. I have been meaning to do a write up of them but you don't necessarily need one to operate the files.

The [scraper](https://github.com/Kr4ken-9/DAB/blob/master/pokebad/scraper.py) collects all of the images of the pokemon.

The [hasher](https://github.com/Kr4ken-9/DAB/blob/master/pokebad/scraper.py) hashes all of the images collected.

Both of the files are documented and should be easy to use. You can modify [this line](https://github.com/Kr4ken-9/DAB/blob/master/pokebad/hashing.py#L25) and change from a 16 bit hash to whatever size bit hash you want or need for your project. Currently DAB uses 16 bit hashes because 8 bit hashes cause collisions where multiple pokemon images have the same hash, obviously causing problems.

If you wanted 8 bit hashes, you would simply change this line:

`h = str(imagehash.dhash(image, 16))`

to this line:

`h = str(imagehash.dhash(image, 8))`

**Comment by PHEXO** [comment]
> I do not publicly provide contact information outside of GitHub.
> 
> I also do not have a way to provide you with 32 character hashes of pokemon. Can I ask you what you need them for? If you want, you can generate hashes of configurable size with some files included in the repo. I have been meaning to do a write up of them but you don't necessarily need one to operate the files.
> 
> The [scraper](https://github.com/Kr4ken-9/DAB/blob/master/pokebad/scraper.py) collects all of the images of the pokemon.
> 
> The [hasher](https://github.com/Kr4ken-9/DAB/blob/master/pokebad/scraper.py) hashes all of the images collected.
> 
> Both of the files are documented and should be easy to use. You can modify [this line](https://github.com/Kr4ken-9/DAB/blob/master/pokebad/hashing.py#L25) and change from a 16 bit hash to whatever size bit hash you want or need for your project. Currently DAB uses 16 bit hashes because 8 bit hashes cause collisions where multiple pokemon images have the same hash, obviously causing problems.
> 
> If you wanted 8 bit hashes, you would simply change this line:
> 
> `h = str(imagehash.dhash(image, 16))`
> 
> to this line:
> 
> `h = str(imagehash.dhash(image, 8))`

i made an autocatcher last year and it worked great but now it dosent work as they have changed the images and the old file that contained the hashes, well it basically dosent work anymore and i used hashlib in the program. so i needed 32 character hashes.

also, i just tried your autocatcher and the same thing is happening. i think they changed the images or something. i'll attach an image.
![Screenshot (8)](https://user-images.githubusercontent.com/51077304/78943796-29257000-7ada-11ea-9a2e-05ef98e6f8ae.png)

**Comment by Kr4ken-9** [comment]
In that case the hashes DAB uses and the hashes you were using were created using different algorithms and wouldn't be compatible.

Can I also ask what time your autocatcher stopped working? I have admittedly not been using the pokecord part of DAB for about two weeks, but two weeks ago it was working.

If the image you are attaching is of the pokemon DAB failed to catch that would be very helpful! I can check if the image matches the one DAB is using and see what caused it to fail.

**Comment by PHEXO** [comment]
> In that case the hashes DAB uses and the hashes you were using were created using different algorithms and wouldn't be compatible.
> 
> Can I also ask what time your autocatcher stopped working? I have admittedly not been using the pokecord part of DAB for about two weeks, but two weeks ago it was working.
> 
> If the image you are attaching is of the pokemon DAB failed to catch that would be very helpful! I can check if the image matches the one DAB is using and see what caused it to fail.

yes that's why i asked you if you could help me get the hashes. you see i am not really good with that stuff and you seem to know about them a lot. i'd basically struggle a lot even if you told me the whole process. 

and the catcher stopped working after 5 mins of usage, it was the first pokemon that spawned. i'd attach the link to the pokemon's image from pokecord's message.
![Capture](https://user-images.githubusercontent.com/51077304/78944796-5d019500-7adc-11ea-953e-00f5a04fff46.PNG)

link:- https://cdn.discordapp.com/attachments/590393765584437261/697924537127272478/PokecordSpawn.jpg

**Comment by Kr4ken-9** [comment]
I could help you but I think it would be a waste of time for the both of us.

There is a similar autocatcher that uses hashlib and was somewhat recently abandoned:
https://github.com/joker-ware/JokerCord

I spoke to some of the people related to this autocatcher and they said that the images are altered on a weekly basis to defeat using hashlib. Whether or not they had any idea what they were talking about I can't say for sure. I did not ever use hashlib because I knew it was possible for this to happen.

The reason this is possible is because hashlib is for cryptographic hashes, which are supposed to be extremely sensitive in that the tiniest change in a file (For example PNGs of pokemon) will make a completely different hash. So, presumably, on a weekly basis the Pokecord maintainers are making small changes to the pokemon images they use to defeat cryptographic hashes.

DAB, and the bot that replaced that autocatcher (https://github.com/joker-ware/nearix-beta) use a different type of hash algorithm called perceptual hashes that are based on changes to how the images appear. That way, the small changes Pokecord maintainers are making won't change the hash of the images.

So, if either you or I took the time to computer all the cryptographic hashes of the pokemon using hashlib, in about a week we would have to do it all over again. This is not the case with perceptual hashes.

That being said, the reason DAB failed to recognize that Pokemon is because that one is something called an "Alolan Meowth." Admittedly, I have no idea what that is. I do not have much knowledge of Pokemon at all. I do know that in this case only the regular Meowth is in the hash database, and I can fix this by manually adding that hash.

**Comment by PHEXO** [comment]
> I could help you but I think it would be a waste of time for the both of us.
> 
> There is a similar autocatcher that uses hashlib and was somewhat recently abandoned:
> https://github.com/joker-ware/JokerCord
> 
> I spoke to some of the people related to this autocatcher and they said that the images are altered on a weekly basis to defeat using hashlib. Whether or not they had any idea what they were talking about I can't say for sure. I did not ever use hashlib because I knew it was possible for this to happen.
> 
> The reason this is possible is because hashlib is for cryptographic hashes, which are supposed to be extremely sensitive in that the tiniest change in a file (For example PNGs of pokemon) will make a completely different hash. So, presumably, on a weekly basis the Pokecord maintainers are making small changes to the pokemon images they use to defeat cryptographic hashes.
> 
> DAB, and the bot that replaced that autocatcher (https://github.com/joker-ware/nearix-beta) use a different type of hash algorithm called perceptual hashes that are based on changes to how the images appear. That way, the small changes Pokecord maintainers are making won't change the hash of the images.
> 
> So, if either you or I took the time to computer all the cryptographic hashes of the pokemon using hashlib, in about a week we would have to do it all over again. This is not the case with perceptual hashes.
> 
> That being said, the reason DAB failed to recognize that Pokemon is because that one is something called an "Alolan Meowth." Admittedly, I have no idea what that is. I do not have much knowledge of Pokemon at all. I do know that in this case only the regular Meowth is in the hash database, and I can fix this by manually adding that hash.

then i think there's another way this could work out, since you know much about imagehash you could just help me with a bit of change in my code so i could use the hashes provided by you.

here's what i was working with few months back:-
`url = message.embeds[0].image.url
description = message.embeds[0].description
prefix = description
hash=""
async with aiohttp.ClientSession() as s:
async with await s.get(url) as resp:
        dat = await resp.content.read()
        hash = hashlib.md5(dat).hexdigest()
print(str(hash))
with open('pokedata.json') as json_file:  
        data = json.load(json_file)`

also, yes alolans are pokemons that are from the alola region and they vary from their origin pokemons in colour, type and nature. if you're adding alolans in the data then just check that it contains the new gen aka Gen8 alolans as well.
and thanks a lot you're helping a lot of people with this.

**Comment by Kr4ken-9** [comment]
Thank you for the information about alolans. I have one more question about them:
Do you know if you have to type `p!catch Alolan Meowth` for alolan pokemon or is it still just `p!catch Meowth`?

Yes, I can help you with that. I do not use aiohttp but the process should be the same.

First, I would import the things we need:
```python
from io import BytesIO
from PIL import Image
import imagehash
```

You will have to install imagehash and Pillow with pip since they are not standard libraries.

Then, I would change:
`dat = await resp.content.read()`

to
`dat = Image.open(BytesIO(await resp.content.read()))`

This could be done on another line too, just make sure to open the data with Image.open() so that it is ready for imagehash.

Then, I would change:
`hash = hashlib.md5(dat).hexdigest()`

to
`hash = imagehash.dhash(dat, 16)`

The final line will convert the `dat` to a 16-bit perceptual hash which is compatible with DAB's list. You can compare them with `str()`

**Comment by PHEXO** [comment]
> Thank you for the information about alolans. I have one more question about them:
> Do you know if you have to type `p!catch Alolan Meowth` for alolan pokemon or is it still just `p!catch Meowth`?
> 
> Yes, I can help you with that. I do not use aiohttp but the process should be the same.
> 
> First, I would import the things we need:
> 
> ```python
> from io import BytesIO
> from PIL import Image
> import imagehash
> ```
> 
> You will have to install imagehash and Pillow with pip since they are not standard libraries.
> 
> Then, I would change:
> `dat = await resp.content.read()`
> 
> to
> `dat = Image.open(BytesIO(await resp.content.read()))`
> 
> This could be done on another line too, just make sure to open the data with Image.open() so that it is ready for imagehash.
> 
> Then, I would change:
> `hash = hashlib.md5(dat).hexdigest()`
> 
> to
> `hash = imagehash.dhash(dat, 16)`
> 
> The final line will convert the `dat` to a 16-bit perceptual hash which is compatible with DAB's list. You can compare them with `str()`

Yep that worked like a charm thanks a lot.

And yes its `p!catch alolan meowth` and not `p!catch meowth` as alolans are different pokemon for pokecord.

Your Thread is a Great help. Keep it up
Hope to see the alolans in the data soon.

**Comment by PHEXO** [comment]
looks like i am kinda stuck again 😩 . this code is working great till the `print(str(hash))` part but idk why but the part after this is not working at all i tried adding a print statement as well but still didn't work. please see if you can help me out. as the hash it prints matches exactly the one with DAB but still smh it thinks hash is not in data.
thanks in advance.

```
        hash=""
        async with aiohttp.ClientSession() as s:
                async with await s.get(url) as resp:
                dat = Image.open(BytesIO(await resp.content.read()))
                hash = imagehash.dhash(dat, 16)
        print(str(hash))
        with open('pokemondata.json') as file:
                data = json.load(file)
        if hash in data:
                await asyncio.sleep(2)
                await message.channel.send(f".catch {data[hash]}")
                await asyncio.sleep(2)
                await message.channel.send(".info latest")
```

**Comment by Kr4ken-9** [comment]
Make sure you are using `str(hash)` to compare the hash with the list of hashes, which are stored as strings. I think this is the problem, because by default `imagehash.dhash()` does not return a string.

You could solve this by changing:
`hash = imagehash.dhash(dat, 16)`

to
`hash = str(imagehash.dhash(dat, 16))`

This might be easier because you won't have to remember to convert it to a string in the future, when comparing it or doing anything else with it.

**Comment by PHEXO** [comment]
> Make sure you are using `str(hash)` to compare the hash with the list of hashes, which are stored as strings. I think this is the problem, because by default `imagehash.dhash()` does not return a string.
> 
> You could solve this by changing:
> `hash = imagehash.dhash(dat, 16)`
> 
> to
> `hash = str(imagehash.dhash(dat, 16))`
> 
> This might be easier because you won't have to remember to convert it to a string in the future, when comparing it or doing anything else with it.

omg how could i have missed that. such a silly mistake 😂 .
Thanks a lot for helping out and just wanted to confirm till when can we expect alolans to be added? :)

**Comment by Kr4ken-9** [comment]
I have all of the images for the different forms of the Pokemon, including alolans. Now it is just a matter of naming them appropriately. This shouldn't take too long, I would expect it done today.

**Comment by PHEXO** [comment]
> I have all of the images for the different forms of the Pokemon, including alolans. Now it is just a matter of naming them appropriately. This shouldn't take too long, I would expect it done today.

Oh that's great news. But it seems like Pokecord has made an Anti-Macro system that automatically ban's account's Now. Just after 3h of usage it botbanned one of my accounts. 
I don't think there's a solution to that.
Thanks for your help.

**Comment by Kr4ken-9** [comment]
There is certainly a solution to that problem but it is a little more broad than you might expect. Very simply, you just need to make your bot account appear human.

There are several ways to do this, some examples are:

1. Always type before sending messages
2. Use variable delays when performing actions (Humans don't have computer-like timing and precision)
3. Don't run the bot for bot-like amounts of time (Humans don't stare at discord for 6 hours straight)
4. Let other people beat you (I think it is reasonable to assume there is a threshold for pokemon that you consistently catch before you get flagged)

There are certainly other ways too, it is just a matter of recognizing and implementing them. Some of these methods are implemented in DAB, and so far I think it works pretty well, a few of my accounts are yet to be banned.

**Comment by Kr4ken-9** [comment]
I ran into some trouble getting the names of different forms of the Pokemon and it took me longer than expected, but I finally was able to add the hashes for all of the relevant ones, including all of the Alolans. You can see my changes in this commit: https://github.com/Kr4ken-9/DAB/commit/41b73291d37952eafefd74675042d277796345c2

**Comment by Kr4ken-9** [comment]
I am closing this issue because there has been no response for over a week, so I am assuming it has been solved.
