### ISSUE TITLE
accounts getting black listed 

### ISSUE THREAD

**Issue by ninfia123** [Kr4ken-9/DAB#79]
2 of me and my friend's acc got black listed at the same time ( we don't share a server or anything, the only mutual thing is DAB)
there is absolutely no way someone could have reported us
It seems like pokerealm bot can detect DAB (but it doesn't black list immediately after you use DAB, its 12h up to 2 days )
don't get me wrong, I ain't blaming DAB or something, just wanted you to know, maybe you could make some changes in code?
thankyou

**Comment by Kr4ken-9** [comment]
The two main ways DAB can be detected is how fast it catches pokemon and for how long DAB is active.

You must configure DAB to appear like a human, because they are looking for bot-like behavior. For instance: If DAB catches pokemon at inhuman speeds, it is a dead giveaway that you are using an automation software. Another example is if you leave DAB on 24/7. Humans need sleep, DAB doesn't, so that will be another detection vector.

I have yet to be blacklisted with reasonable catch delays and making use of catching intervals.

**Comment by ninfia123** [comment]
oh yea i see what you mean now
after being black listed when i wasn't using dab, it was made clear
ty
